version: '3'

services:

  web:
    build:
      context: '.'
      dockerfile: '/Dockerfile'
    env_file:
      - environments/local.env
    environment:
      DEV: ${DEV}
    deploy:
      replicas: 2
    depends_on:
      - db
    ports:
      - 8080:8080  # the first container port listed is where HTTP requests are sent

volumes:
  db-data:
    labels:
      shipyard.deploy.disk.size: 10Gi
